name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Installeer workloads per platform om vastlopen te voorkomen
      - name: Install MAUI Android workload
        run: dotnet workload install maui-android

      - name: Install MAUI iOS workload
        run: dotnet workload install ios

      - name: Install MAUI MacCatalyst workload
        run: dotnet workload install maccatalyst

      # Restore dependencies per platform (optioneel, maar stabieler)
      - name: Restore Android
        run: dotnet restore -f net8.0-android

      - name: Restore iOS
        run: dotnet restore -f net8.0-ios

      - name: Restore MacCatalyst
        run: dotnet restore -f net8.0-maccatalyst

      # Build per platform
      - name: Build Android
        run: dotnet build -f net8.0-android --configuration Release --no-restore

      - name: Build iOS
        run: dotnet build -f net8.0-ios --configuration Release --no-restore

      - name: Build MacCatalyst
        run: dotnet build -f net8.0-maccatalyst --configuration Release --no-restore

      # Run unit tests (gebruik de juiste target framework als tests specifiek zijn)
      - name: Run unit tests Android
        run: dotnet test -f net8.0-android --configuration Release --no-build --no-restore --verbosity normal

      - name: Run unit tests iOS
        run: dotnet test -f net8.0-ios --configuration Release --no-build --no-restore --verbosity normal

      - name: Run unit tests MacCatalyst
        run: dotnet test -f net8.0-maccatalyst --configuration Release --no-build --no-restore --verbosity normal
